spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:13306/mydb
    username: root
    password: '{cipher}AQCJ9sQ/CPuWaU5Nxo7/vsvs0RX5FslDxtm/GfNF5XoIhGSOWJc+uzjhxHw8Hq3gaVgoyfYmKxIoDVRqC3SfzwhP1+YESeiDwB7oabRYkB1kHVi8lDCrVtQfagR8/UEjFtjMuGC5wj+Ff2ereZyPCJS1hPzgzkeCj1Tcf725rNZu0Oc2Z8rzsSRtb869s+zfaFVBtpOs0hWiGBxx037zyJ00zn2ATq0hx4oJzNojEUm+/xdV+GjtXEXSa/tgEk2acvdwIQ51T73AQaKUB6ZtWraE9MltDzdc/7iksD50vptohnOEyBpXwPDxYfVDy2w3w732dekAX5Gw/6HSOvqiuziVR42O2DvFtZul2DL0cRuFGfr/tD9dWX4yUrMtbSl88Xo='
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: '{cipher}AQCnPnOrm1LV9hh/6eFlOvcMFBGXKx2PLDTrGqR/XB6qaarJsySQdvREXbdWkFYU7AYxEtCyMvK9FcsWgJtb0/37DA6jS52ZE7XWNb0Uug7ki3KOhO+yNUU4Jp40mT4qLDNj7bS+rbaK4ksJt7/j9vBdmegyB17CGMabz9wuWv+nnpahdZ6tjhBF3QO7hLOpJUMz8mawBF9XFOjraibrQMYwssutAQ5CNM6PmebS5ttuJneP3ENJUEpAJpGzg5lPNdonDe/6xUb0PUchMVMeTF5Rw7czE9UBZEfnVHcJtuD9mQKkga8/H+ye+vcdvPMHuqRv1cOpLyoD4Jxsy7os5aypKhhToTLk+YJ0qWEMQ4vLHG6/F9+91KKy5NJX1a/s0N0='