spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Documents/study/spring-cloud-workspace/db/msa
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: '{cipher}AQCnPnOrm1LV9hh/6eFlOvcMFBGXKx2PLDTrGqR/XB6qaarJsySQdvREXbdWkFYU7AYxEtCyMvK9FcsWgJtb0/37DA6jS52ZE7XWNb0Uug7ki3KOhO+yNUU4Jp40mT4qLDNj7bS+rbaK4ksJt7/j9vBdmegyB17CGMabz9wuWv+nnpahdZ6tjhBF3QO7hLOpJUMz8mawBF9XFOjraibrQMYwssutAQ5CNM6PmebS5ttuJneP3ENJUEpAJpGzg5lPNdonDe/6xUb0PUchMVMeTF5Rw7czE9UBZEfnVHcJtuD9mQKkga8/H+ye+vcdvPMHuqRv1cOpLyoD4Jxsy7os5aypKhhToTLk+YJ0qWEMQ4vLHG6/F9+91KKy5NJX1a/s0N0='

order-service:
  url: http://order-service/order-service/%s/orders
  exception:
    order-is-empty: User's orders is empty_2.